(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var l=this||self,aa=function(a,b){a:{var c=["CLOSURE_FLAGS"];for(var d=l,g=0;g<c.length;g++)if(d=d[c[g]],null==d){c=null;break a}c=d}a=c&&c[a];return null!=a?a:b},ba=function(a){return a};var ca=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};var da=aa(610401301,!1),ea=aa(572417392,!0);var p;const fa=l.navigator;p=fa?fa.userAgentData||null:null;function ha(a){return da?p?p.brands.some(({brand:b})=>b&&-1!=b.indexOf(a)):!1:!1}function q(a){var b;a:{if(b=l.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)};function r(){return da?!!p&&0<p.brands.length:!1}function ia(){return r()?ha("Chromium"):(q("Chrome")||q("CriOS"))&&!(r()?0:q("Edge"))||q("Silk")};var ja=r()?!1:q("Trident")||q("MSIE");!q("Android")||ia();ia();q("Safari")&&(ia()||(r()?0:q("Coast"))||(r()?0:q("Opera"))||(r()?0:q("Edge"))||(r()?ha("Microsoft Edge"):q("Edg/"))||r()&&ha("Opera"));var ka={},t=null;var la="undefined"!==typeof Uint8Array,ma=!ja&&"function"===typeof btoa;var na=!ea;let oa=!ea;function v(a){return Array.prototype.slice.call(a)};var w;w="function"===typeof Symbol&&"symbol"===typeof Symbol()?Symbol():void 0;var pa=w?(a,b)=>{a[w]|=b}:(a,b)=>{void 0!==a.i?a.i|=b:Object.defineProperties(a,{i:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function qa(a){const b=x(a);1!==(b&1)&&(Object.isFrozen(a)&&(a=v(a)),y(a,b|1))}function B(a,b,c){return c?a|b:a&~b}var x=w?a=>a[w]|0:a=>a.i|0,C=w?a=>a[w]:a=>a.i,y=w?(a,b)=>{a[w]=b}:(a,b)=>{void 0!==a.i?a.i=b:Object.defineProperties(a,{i:{value:b,configurable:!0,writable:!0,enumerable:!1}})};function ra(){var a=[];pa(a,1);return a}
function sa(a,b){y(b,(a|0)&-14591)}function ta(a,b){y(b,(a|34)&-14557)}function D(a){a=a>>14&1023;return 0===a?536870912:a};var E={},ua={};function va(a){return!(!a||"object"!==typeof a||a.v!==ua)}function F(a){return null!==a&&"object"===typeof a&&!Array.isArray(a)&&a.constructor===Object}let wa,xa=!ea;function ya(a,b,c){if(!Array.isArray(a)||a.length)return!1;const d=x(a);if(d&1)return!0;if(!(b&&(Array.isArray(b)?b.includes(c):b.has(c))))return!1;y(a,d|1);return!0}var G;const za=[];y(za,55);G=Object.freeze(za);class Aa{}class Ba{}Object.freeze(new Aa);Object.freeze(new Ba);function Ca(a){if(null==a)return a;if("string"===typeof a){if(!a)return;a=+a}if("number"===typeof a)return Number.isFinite(a)?a|0:void 0}function Da(a,b,c){if(null!=a&&"object"===typeof a&&a.j===E)return a;if(Array.isArray(a)){var d=x(a),g=d;0===g&&(g|=c&32);g|=c&2;g!==d&&y(a,g);return new b(a)}};let I;function Ea(a,b){I=b;a=new a(b);I=void 0;return a};function Fa(a,b){return Ga(b)}
function Ga(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "boolean":return a?1:0;case "object":if(a){if(Array.isArray(a))return xa||!ya(a,void 0,9999)?a:void 0;if(la&&null!=a&&a instanceof Uint8Array){if(ma){for(var b="",c=0,d=a.length-10240;c<d;)b+=String.fromCharCode.apply(null,a.subarray(c,c+=10240));b+=String.fromCharCode.apply(null,c?a.subarray(c):a);a=btoa(b)}else{void 0===b&&(b=0);if(!t){t={};c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split("");d=
["+/=","+/","-_=","-_.","-_"];for(var g=0;5>g;g++){var e=c.concat(d[g].split(""));ka[g]=e;for(var h=0;h<e.length;h++){var f=e[h];void 0===t[f]&&(t[f]=h)}}}b=ka[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(g=e=0;e<a.length-2;e+=3){var k=a[e],m=a[e+1];f=a[e+2];h=b[k>>2];k=b[(k&3)<<4|m>>4];m=b[(m&15)<<2|f>>6];f=b[f&63];c[g++]=""+h+k+m+f}h=0;f=d;switch(a.length-e){case 2:h=a[e+1],f=b[(h&15)<<2]||d;case 1:a=a[e],c[g]=""+b[a>>2]+b[(a&3)<<4|h>>4]+f+d}a=c.join("")}return a}}}return a};function Ha(a,b,c){a=v(a);var d=a.length;const g=b&256?a[d-1]:void 0;d+=g?-1:0;for(b=b&512?1:0;b<d;b++)a[b]=c(a[b]);if(g){b=a[b]={};for(const e in g)b[e]=c(g[e])}return a}function Ia(a,b,c,d,g,e){if(null!=a){if(Array.isArray(a))a=g&&0==a.length&&x(a)&1?void 0:e&&x(a)&2?a:Ja(a,b,c,void 0!==d,g,e);else if(F(a)){const h={};for(let f in a)h[f]=Ia(a[f],b,c,d,g,e);a=h}else a=b(a,d);return a}}
function Ja(a,b,c,d,g,e){const h=d||c?x(a):0;d=d?!!(h&32):void 0;a=v(a);for(let f=0;f<a.length;f++)a[f]=Ia(a[f],b,c,d,g,e);c&&c(h,a);return a}function Ka(a){return a.j===E?a.toJSON():Ga(a)};function La(a,b,c=ta){if(null!=a){if(la&&a instanceof Uint8Array)return b?a:new Uint8Array(a);if(Array.isArray(a)){var d=x(a);if(d&2)return a;b&&(b=0===d||!!(d&32)&&!(d&64||!(d&16)));return b?(y(a,(d|34)&-12293),a):Ja(a,La,d&4?ta:c,!0,!1,!0)}a.j===E&&(c=a.g,d=C(c),a=d&2?a:Ea(a.constructor,Ma(c,d,!0)));return a}}function Ma(a,b,c){const d=c||b&2?ta:sa,g=!!(b&32);a=Ha(a,b,e=>La(e,g,d));pa(a,32|(c?2:0));return a}function Na(a){const b=a.g,c=C(b);return c&2?Ea(a.constructor,Ma(b,c,!1)):a};var Pa=function(a,b){a=a.g;return Oa(a,C(a),b)},Oa=function(a,b,c,d){if(-1===c)return null;if(c>=D(b)){if(b&256)return a[a.length-1][c]}else{var g=a.length;if(d&&b&256&&(d=a[g-1][c],null!=d))return d;b=c+(+!!(b&512)-1);if(b<g)return a[b]}};function J(a,b,c,d,g){var e=D(b);if(c>=e||g){g=b;if(b&256)e=a[a.length-1];else{if(null==d)return g;e=a[e+(+!!(b&512)-1)]={};g|=256}e[c]=d;g!==b&&y(a,g);return g}a[c+(+!!(b&512)-1)]=d;b&256&&(a=a[a.length-1],c in a&&delete a[c]);return b}
var Q=function(a,b,c){return void 0!==M(a,b,N(a,O,c))},Qa=function(a,b){a=Pa(a,b);return null==a||"boolean"===typeof a?a:"number"===typeof a?!!a:void 0};function Ra(a){return!!(2&a)&&!!(4&a)||!!(2048&a)}function Sa(a,b,c,d){const g=a.g;let e=C(g);if(e&2)throw Error();J(g,e,b,("0"===d?0===Number(c):c===d)?void 0:c);return a}var N=function(a,b,c){a=a.g;return Ta(a,C(a),b)===c?c:-1};
function Ta(a,b,c){let d=0;for(let g=0;g<c.length;g++){const e=c[g];null!=Oa(a,b,e)&&(0!==d&&(b=J(a,b,d)),d=e)}return d}
var M=function(a,b,c,d){a=a.g;let g=C(a);const e=Oa(a,g,c,d);b=Da(e,b,g);b!==e&&null!=b&&J(a,g,c,b,d);return b},R=function(a,b,c){b=M(a,b,c,!1);if(null==b)return b;a=a.g;let d=C(a);if(!(d&2)){const g=Na(b);g!==b&&(b=g,J(a,d,c,b,!1))}return b},Xa=function(a,b){a=a.g;var c=C(a),d=c,g=!(2&c),e=!!(2&d),h=e?1:2;c=1===h;h=2===h;g&&(g=!e);e=Oa(a,d,b);e=Array.isArray(e)?e:G;var f=x(e);const k=!!(4&f);if(!k){var m=f;0===m&&(m=Va(m,d));m=B(m,1,!0);f=e;var u=d,n=Wa;const K=!!(2&m);K&&(u=B(u,2,!0));let P=!K,
z=!0,A=0,L=0;for(;A<f.length;A++){const H=Da(f[A],n,u);if(H instanceof n){if(!K){const Ua=!!(x(H.g)&2);P&&(P=!Ua);z&&(z=Ua)}f[L++]=H}}L<A&&(f.length=L);m=B(m,4,!0);m=B(m,16,z);m=B(m,8,P);y(f,m);K&&Object.freeze(f);f=m}m=!!(8&f)||c&&!e.length;if(g&&!m){Ra(f)&&(e=v(e),f=Va(f,d),d=J(a,d,b,e));g=e;for(m=0;m<g.length;m++)u=g[m],n=Na(u),u!==n&&(g[m]=n);f=B(f,8,!0);f=B(f,16,!g.length);y(g,f)}Ra(f)||(g=f,c?f=B(f,!e.length||16&f&&(!k||32&f)?2:2048,!0):f=B(f,32,!1),f!==g&&y(e,f),c&&Object.freeze(e));h&&Ra(f)&&
(e=v(e),f=Va(f,d),y(e,f),J(a,d,b,e));return e};function Va(a,b){a=B(a,2,!!(2&b));a=B(a,32,!!(32&b)&&!1);return a=B(a,2048,!1)}var S=function(a,b){a=Qa(a,b);return null!=a?a:!1},T=function(a,b){a=Ca(Pa(a,b));return null!=a?a:0},U=function(a,b){a=Pa(a,b);a=null==a||"string"===typeof a?a:void 0;return null!=a?a:""};var V=class{constructor(a){a:{null==a&&(a=I);I=void 0;if(null==a){var b=96;a=[]}else{if(!Array.isArray(a))throw Error();b=x(a);if(b&64)break a;var c=a;b|=64;var d=c.length;if(d&&(--d,F(c[d]))){b|=256;c=d-(+!!(b&512)-1);if(1024<=c)throw Error();b=b&-16760833|(c&1023)<<14}}y(a,b)}this.g=a}toJSON(){if(wa)var a=Ya(this,this.g,!1);else a=Ja(this.g,Ka,void 0,void 0,!1,!1),a=Ya(this,a,!0);return a}};V.prototype.j=E;V.prototype.toString=function(){return Ya(this,this.g,!1).toString()};
function Ya(a,b,c){const d=a.constructor.l;var g=C(c?a.g:b),e=D(g),h=!1;if(d&&xa){if(!c){b=v(b);var f;if(b.length&&F(f=b[b.length-1]))for(h=0;h<d.length;h++)if(d[h]>=e){Object.assign(b[b.length-1]={},f);break}h=!0}e=b;c=!c;f=C(a.g);a=D(f);f=+!!(f&512)-1;var k;for(let H=0;H<d.length;H++){var m=d[H];if(m<a){m+=f;var u=e[m];null==u?e[m]=c?G:ra():c&&u!==G&&qa(u)}else{if(!k){var n=void 0;e.length&&F(n=e[e.length-1])?k=n:e.push(k={})}u=k[m];null==k[m]?k[m]=c?G:ra():c&&u!==G&&qa(u)}}}k=b.length;if(!k)return b;
let K,P;if(F(n=b[k-1])){a:{var z=n;e={};c=!1;for(var A in z){a=z[A];if(Array.isArray(a)){f=a;if(!oa&&ya(a,d,+A)||!na&&va(a)&&0===a.size)a=null;a!=f&&(c=!0)}null!=a?e[A]=a:c=!0}if(c){for(let H in e){z=e;break a}z=null}}z!=n&&(K=!0);k--}for(g=+!!(g&512)-1;0<k;k--){A=k-1;n=b[A];if(!(null==n||!oa&&ya(n,d,A-g)||!na&&va(n)&&0===n.size))break;P=!0}if(!K&&!P)return b;var L;h?L=b:L=Array.prototype.slice.call(b,0,k);b=L;h&&(b.length=k);z&&b.push(z);return b};var Wa=class extends V{},W=[2,3,4];var Za=class extends V{};var $a=class extends V{};var ab=class extends V{};ab.l=[6];var bb=class extends V{constructor(){super()}};var cb=class extends V{constructor(){super()}},db=[2];var eb=class extends V{};eb.l=[2];var fb=class extends V{};var gb=class extends V{};var hb=class extends V{};var ib=function(a){return b=>{if(null==b||""==b)b=new a;else{b=JSON.parse(b);if(!Array.isArray(b))throw Error(void 0);pa(b,32);b=Ea(a,b)}return b}}(class extends V{}),O=[2,3,4,5,6,7];var jb;var kb=class{constructor(a){this.h=a}toString(){return this.h+""}},lb={},mb=function(a){if(void 0===jb){var b=null;var c=l.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:ba,createScript:ba,createScriptURL:ba})}catch(d){l.console&&l.console.error(d.message)}jb=b}else jb=b}a=(b=jb)?b.createScriptURL(a):a;return new kb(a,lb)};var nb=function(){this.h=document||{cookie:""}};
nb.prototype.set=function(a,b,c){let d,g,e,h=!1,f;"object"===typeof c&&(f=c.A,h=c.B||!1,e=c.domain||void 0,g=c.path||void 0,d=c.s);if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');void 0===d&&(d=-1);this.h.cookie=a+"="+b+(e?";domain="+e:"")+(g?";path="+g:"")+(0>d?"":0==d?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(Date.now()+1E3*d)).toUTCString())+(h?";secure":"")+(null!=f?";samesite="+f:"")};
nb.prototype.get=function(a,b){const c=a+"=",d=(this.h.cookie||"").split(";");for(let g=0,e;g<d.length;g++){e=ca(d[g]);if(0==e.lastIndexOf(c,0))return e.slice(c.length);if(e==a)return""}return b};
nb.prototype.clear=function(){var a=(this.h.cookie||"").split(";");const b=[];var c=[];let d,g;for(let e=0;e<a.length;e++)g=ca(a[e]),d=g.indexOf("="),-1==d?(b.push(""),c.push(g)):(b.push(g.substring(0,d)),c.push(g.substring(d+1)));for(c=b.length-1;0<=c;c--)a=b[c],this.get(a),this.set(a,"",{s:0,path:void 0,domain:void 0})};/*

 SPDX-License-Identifier: Apache-2.0
*/
function ob(a,...b){if(0===b.length)return mb(a[0]);let c=a[0];for(let d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return mb(c)};class pb{constructor(){this.m=new nb;this.h="";this.o=a=>{a:{let k;try{k=ib(a.data)}catch(m){break a}if(Q(k,ab,4)){var b=R(k,ab,N(k,O,4));var c=Xa(b,6);var d;c.length&&(d=qb(c));c={event:U(b,1)||void 0,category:U(b,2)||void 0,action:U(b,3)||void 0,label:U(b,4)||void 0,value:T(b,5)||void 0,nonInteraction:S(b,13)?"True":"False",additionalParams:d||void 0};if(void 0!==M(b,$a,12,!1)){var g=R(b,$a,12);c.recommendations={targetPage:U(g,1),targetType:T(g,2),targetRank:T(g,3),targetIdenticalDescriptions:T(g,
4),targetTitleWords:T(g,5),targetDescriptionWords:T(g,6),experiment:U(g,7)};d="";for(var e of window.dataLayer)if("experiment"in e&&"baseIds"in e.experiment){d=e.experiment.baseIds;break}(d=rb(d,U(g,7)))&&S(g,8)&&(c.experiment={ids:d})}else c.recommendations={targetPage:void 0,targetType:void 0,targetRank:void 0,targetIdenticalDescriptions:void 0,targetTitleWords:void 0,targetDescriptionWords:void 0};if(!("experiment"in c))for(var h of window.dataLayer)if("experiment"in h&&"ids"in h.experiment&&h.experiment.ids){c.experiment=
{ids:h.experiment.ids};break}e=R(b,Za,11);if(void 0!==M(b,Za,11,!1)&&null!==e){e=sb(e);for(var f of Object.keys(e))c[f]=e[f]}window.dataLayer.push(c)}else if(Q(k,eb,3)){f=R(k,eb,N(k,O,3));e=Xa(f,2);let m;e.length&&(m=qb(e));e={event:"trackPageview",pageName:U(f,1),additionalParams:m||void 0,nonInteraction:S(f,3)||void 0,ratingsCount:T(f,4)||void 0,ratingsValue:T(f,5)||void 0};h=R(f,Za,6);if(void 0!==M(f,Za,6,!1)&&null!==h){f=sb(h);for(b of Object.keys(f))e[b]=f[b]}window.dataLayer.push(e)}else Q(k,
fb,7)?(f=R(k,fb,N(k,O,7)),window.dataLayer.push({parentContext:{referrer:U(f,2)||"",_ga_devsiteCookie:U(f,1)||""}})):Q(k,gb,6)?(f=R(k,gb,N(k,O,6)),e=this.h,h=R(f,$a,9)||new $a,b=U(f,10)||void 0,f={experiment:{ids:(S(h,8)?rb(b,U(h,7)):b)||void 0,baseIds:b||void 0},hostContext:{internalUser:U(f,1)||void 0,pageType:U(f,8)||void 0,projectName:U(f,6)||void 0,signedIn:U(f,2)||void 0,tenant:U(f,5)||void 0,thirdPartyCookieAccepted:e.length?"True":"False"},language:{machineTranslated:U(f,7)||void 0,requested:U(f,
3)||void 0,served:U(f,4)||void 0},recommendations:{sourcePage:U(h,1),sourceType:T(h,2),sourceRank:T(h,3),sourceIdenticalDescriptions:T(h,4),sourceTitleWords:T(h,5),sourceDescriptionWords:T(h,6),experiment:U(h,7)}},window.dataLayer.push(f)):Q(k,hb,5)?(f=R(k,hb,N(k,O,5)),window.dataLayer.push({originalUrlParameters:{dclid:U(f,1)||void 0,gclid:U(f,2)||void 0,utmCampaign:U(f,3)||void 0,utmContent:U(f,4)||void 0,utmCreativeFormat:U(f,8)||void 0,utmMarketingTactic:U(f,10)||void 0,utmMedium:U(f,5)||void 0,
utmSource:U(f,6)||void 0,utmSourcePlatform:U(f,9)||void 0,utmTerm:U(f,7)||void 0}})):null!=Qa(k,N(k,O,2))&&(window.dataLayer=window.dataLayer||[],window.dataLayer.push({"gtm.start":(new Date).getTime(),event:"gtm.js"}),e=document,f=e.getElementsByTagName("script")[0],e=e.createElement("script"),e.async=!0,h=ob`//www.googletagmanager.com/gtm.js?id=GTM-PBZPJDG`,e.src=h instanceof kb&&h.constructor===kb?h.h:"type_error:TrustedResourceUrl",(h=(h=null==(g=(c=(e.ownerDocument&&e.ownerDocument.defaultView||
window).document).querySelector)?void 0:g.call(c,"script[nonce]"))?h.nonce||h.getAttribute("nonce")||"":"")&&e.setAttribute("nonce",h),f.parentNode.insertBefore(e,f))}};window.addEventListener("message",this.o)}u(a){this.h=this.m.get("_ga_devsite")||"";var b=new bb;if(null!=a&&"boolean"!==typeof a){var c=typeof a;throw Error(`Expected boolean but got ${"object"!=c?c:a?Array.isArray(a)?"array":c:"null"}: ${a}`);}a=Sa(b,1,a,!1);b=this.h;if(null!=b&&"string"!==typeof b)throw Error();b=Sa(a,2,b,"");a=
new cb;null==b&&(b=void 0);var d=a.g;let g=C(d);if(g&2)throw Error();let e=Ta(d,g,db);e&&2!==e&&null!=b&&(g=J(d,g,e));J(d,g,2,b);if(window.parent!==window){b=window.parent;d=b.postMessage;a:{wa=!0;try{c=JSON.stringify(a.toJSON(),Fa);break a}finally{wa=!1}c=void 0}d.call(b,c,"*")}}}pb.prototype.notifyIframeReady=pb.prototype.u;
function qb(a){const b={};for(const c of a){a=U(c,1);let d;U(c,N(c,W,2))?d=U(c,N(c,W,2)):T(c,N(c,W,3))?d=T(c,N(c,W,3)):null!=Qa(c,N(c,W,4))&&(d=S(c,N(c,W,4))?"True":"False");b[a]=d}return b}
function sb(a){const b={};if(!a)return b;b.hasProfile=S(a,6)?"True":"False";b.practitionerType=U(a,1)||"Property not set";b.profileCreationMethod=U(a,4)||"Property not set";b.profileHasInterests=S(a,12)?"True":"False";b.profileInterests=U(a,13)||"Property not set";b.profileHasJobTitle=S(a,10)?"True":"False";b.profileHasLocation=S(a,7)?"True":"False";b.profileHasPronoun=S(a,9)?"True":"False";b.profileIsPublic=S(a,8)?"True":"False";b.profileSocialLinks=U(a,11)||"Property not set";b.profileBadgeEmailOptIn=
S(a,5)?"True":"False";b.profileFeedbackEmailOptIn=S(a,2)?"True":"False";b.profileNewsletterEmailOptIn=S(a,3)?"True":"False";return b}function rb(a,b){if(a||b){if(a&&!b)return a;if(b&&!a)return b;b=new Set(b.split(","));a=[...(new Set([...(new Set(a.split(","))),...b]))];a.sort();return a.join(",")}}var tb=pb,X=["AnalyticsLibrary"],Y=l;X[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+X[0]);
for(var Z;X.length&&(Z=X.shift());)X.length||void 0===tb?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=tb;}).call(this);
