(function(_ds){var window=this;var Sca=function(a){const b=a.ox,c=a.cd,d=a.yu;a=a.Mv;let e;e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle"><span class="devsite-nav-title" role="heading" aria-level="2"><span class="devsite-nav-text">On this page</span></span>';c&&(e=e+'<button type="button" title="'+_ds.dD("Expand/collapse contents"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";const f=b.length;for(let h=0;h<f;h++){var g=b[h];e+='<li class="devsite-nav-item"'+
(c&&g.index<a?" visible":"")+'><a href="#'+_ds.Y(g.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.Y(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.Y(h)+'" track-metadata-link-destination="#'+_ds.Y(g.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.V(g.text)+"</span></a>";if(g.children.length){e+='<ul class="devsite-nav-list">';
g=g.children;const k=g.length;for(let l=0;l<k;l++){const m=g[l];e+='<li class="devsite-nav-item"'+(c&&m.index<a?" visible":"")+'><a href="#'+_ds.Y(m.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.Y(h)+"."+_ds.Y(l)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.Y(h)+"."+_ds.Y(l)+'" track-metadata-link-destination="#'+
_ds.Y(m.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.V(m.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Try it</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Try it!</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.dD("Expand/collapse contents"),e+='"></button></li>');return(0,_ds.U)(e+"</ul>")};var B8=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.cd?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),Tca(a,b),a.qa=!0):a.Ab()}},Vca=async function(a){await Uca(a);if(a.h){var b=`#${a.h.id}`,c=encodeURI(b);b=a.ma.get(b)||a.ma.get(c);a.o!==b&&(a.o&&a.o.classList.remove("devsite-nav-active"),b&&(b.classList.add("devsite-nav-active"),a.v&&("scrollIntoViewIfNeeded"in b?b.scrollIntoViewIfNeeded():b.scrollIntoView()),
a.o=b))}},Wca=function(a){a.cd||a.eventHandler.listen(document.body,"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),()=>{a.va.Ua()});a.eventHandler.listen(document.body,"devsite-content-updated",()=>{B8(a)})},Xca=async function(a){if("IntersectionObserver"in _ds.Nj()){a.Xb&&a.Xb.disconnect();var b=document.querySelector("devsite-header");let c=152;b&&(await customElements.whenDefined("devsite-header"),
(b=b.oa())&&(c=b));a.Xb=new IntersectionObserver(d=>{for(const e of d)e.isIntersecting?a.ea.add(e.target):a.ea.delete(e.target);a.va.Ua()},{rootMargin:`${c}px 0px 0px 0px`,threshold:[0,1]})}a.ra.g()},Uca=async function(a){let b=0;var c=document.querySelector("devsite-header");c&&(await customElements.whenDefined("devsite-header"),b=c.v());c=a.j.findIndex(e=>a.ea.has(e)&&e.getBoundingClientRect().top>=b);const d=a.j[c];if(d){const e=await Yca();d.getBoundingClientRect().top-b>e&&0<c?a.h=a.j[c-1]:a.h=
d}else a.h&&a.h.getBoundingClientRect().top>window.innerHeight&&(c=a.j.indexOf(a.h),0<c&&(a.h=a.j[c-1]))},Tca=function(a,b){const c=[];let d=!1,e="";switch(a.getAttribute("depth")){case "1":e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.j=[...b.querySelectorAll(e)].filter(f=>f.id&&f.dataset.text).filter(f=>Zca(f));for(const [f,g]of a.j.entries())b=
g,b={id:b.id,level:b.tagName.toLowerCase(),text:b.dataset.text,children:[],index:f},"h2"===b.level?(c.push(b),d=!0):d?c[c.length-1].children.push(b):c.push(b);_ds.tb(a.oa,c,a.ua.bind(a))&&a.qa||(c.length?($ca(a,c),a.show(),a.cd||ada(a)):a.Ab(),a.oa=c)},Zca=function(a){return _ds.Dl.find(b=>!!_ds.lk(a,null,b,6))||_ds.lk(a,"devsite-selector",null,6)||_ds.lk(a,null,"devsite-dialog",3)?!1:!0},$ca=function(a,b){const c=_ds.O(Sca,{ox:b,cd:a.cd,yu:!!document.body.querySelector("devsite-apix, .devsite-apix"),
Mv:8>b.length?8:5});a.v&&(b=c.querySelector("button.devsite-show-apix"))&&a.eventHandler.listen(b,"click",()=>{a.dispatchEvent(new CustomEvent("devsite-concierge-open-panel",{bubbles:!0,composed:!0,detail:{mw:"devsite-concierge-api-explorer-panel"}}))});b=c.querySelectorAll("a.devsite-nav-title");for(const d of b){b=d;const e=b.hash,f=encodeURI(b.hash);a.ma.set(e,b);a.ma.set(f,b)}_ds.Sj(a);a.cd&&_ds.E(a,"hidden","",c);a.appendChild(c);if(a.cd){if(8<a.getElementsByClassName("devsite-nav-item").length){for(const d of a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"))a.eventHandler.listen(d,
"click",()=>{a.hasAttribute("expanded")?a.removeAttribute("expanded"):_ds.E(a,"expanded","")});_ds.E(a,"expandable","")}else a.removeAttribute("expandable");setTimeout(()=>{c.removeAttribute("hidden")},0)}},ada=async function(a){await a.ra.promise;if(a.Xb){a.Xb.disconnect();a.ea.clear();a.o&&a.o.classList.remove("devsite-nav-active");a.o=null;for(const b of a.j)a.Xb.observe(b)}},Yca=async function(){let a=0,b=0;const c=document.querySelector("devsite-header");c&&(await customElements.whenDefined("devsite-header"),
a=c.v(),b=c.oa());return Math.max(b-a,Math.floor((window.innerHeight-a)/5))},C8=class extends _ds.F{static get observedAttributes(){return["max-height","offset"]}constructor(){super();this.eventHandler=new _ds.H;this.ra=new _ds.Ne;this.ea=new Set;this.ma=new Map;this.xa=new _ds.Am(()=>void B8(this),16);this.va=new _ds.Am(()=>void Vca(this),33);this.h=this.o=null;this.j=[];this.qa=!1;this.Xb=null;this.v=this.cd=!1;this.oa=[];_ds.Si(this,(0,_ds.t)`disabled`,(0,_ds.t)`has-sidebar`,(0,_ds.t)`hidden`,
(0,_ds.t)`expandable`,(0,_ds.t)`expanded`,(0,_ds.t)`visible`)}connectedCallback(){this.cd=this.hasAttribute("devsite-toc-embedded");this.v=document.body.hasAttribute("concierge");B8(this);Wca(this)}disconnectedCallback(){this.Ab();this.qa=!1;_ds.I(this.eventHandler)}Oj(a){a=a&&"false"===a.toLowerCase();this.oa=[];_ds.Sj(this);a?(_ds.E(this,"disabled",""),this.Ab()):(this.removeAttribute("disabled"),this.xa.Ua())}Ab(){_ds.Sj(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));
this.removeAttribute("visible");_ds.E(this,"hidden","");if(!this.cd&&!this.v){const a=document.querySelector(".devsite-main-content");a&&a.removeAttribute("has-sidebar")}}show(){this.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));this.removeAttribute("hidden");_ds.E(this,"visible","");if(!this.cd){if(!this.v){const a=document.querySelector(".devsite-main-content");a&&_ds.E(this,"has-sidebar","",a)}Xca(this)}}ua(a,b){let c=!0;if(a.children.length||b.children.length)c=_ds.tb(a.children,
b.children,this.ua.bind(this));return c&&a.id===b.id&&a.text===b.text}};C8.prototype.renderUpdatedContent=C8.prototype.Oj;C8.prototype.disconnectedCallback=C8.prototype.disconnectedCallback;C8.prototype.connectedCallback=C8.prototype.connectedCallback;try{customElements.define("devsite-toc",C8)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
